trigger: none

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: templates
    type: github
    name: swellaby/azure-pipelines-templates
    endpoint: swellaby

steps:
- template: templates/yml/node/combo/npm-build-validation-xunit-cobertura.yml@templates
  parameters:
    publishTestResults:
      taskDisplayName: 'Publish unit test results'
      testResultsFormat: 'JUnit'
      testResultsFiles: 'xunit.xml'
      searchFolder: '$(Build.SourcesDirectory)/.testresults/unit'
      testRunTitle: 'cobertura-transform::Unit Tests::Linux PR - Build $(Build.BuildId)'

- script: |
    bash <(curl -s https://codecov.io/bash) -t $(codecovToken)
  displayName: 'Publish coverage to Codecov'
